### ISSUE TITLE
Incomplete chord conversion tables

### ISSUE THREAD

**Issue by ajcz** [michgz/ac7maker#3]
The CT-X keyboards recognizes chords (see [User’s Guide](https://support.casio.com/en/manual/008/Web_CTX3000-ES-1B_EN.pdf), page 147 or A-2) that are not listed in [the conversion tables file](https://github.com/michgz/ac7maker/blob/740cc3/Documentation%20of%20Casio%20formats/Conversion%20Tables%20(key%20of%20C).csv#L1).  Is there any reason why these are left out?

**Comment by michgz** [comment]
Good call, I've made a start at adding the missing ones. I'll close this ticket once it's complete.
