### ISSUE TITLE
“f-root” conversion tables

### ISSUE THREAD

**Issue by ajcz** [michgz/ac7maker#4]
There are currently 16 chord conversion tables in **ac7maker.py**; the 3 “f-root” tables documented on page 88 or EN-87 of the User’s Guide are missing.  An “f-root” table makes the first note the root note upon chord change (so isn’t really a table in the usual sense).  Assuming you measured the table data by recording a chromatic scale on C and then playing every chord on C, the data you got for an “f-root” rule and its standard counterpart should be identical because there’s no change of root.

There are 4 pairs of identical tables in the current conversion tables file:
* 2 (Chord basic (for chord parts)) and 28;
* 4 (Chord var 3 (for chord parts)) and 29;
* 18 and 31; and
* 19 and 32.

So it doesn’t look like the missing “f-root” table numbers are within the 0–35 range.

You have [said previously](https://github.com/michgz/ac7maker/commit/608ff8) that using table numbers above 35 gave “incoherent results”.  I’m wondering if you missed something in those 220 tables, or maybe the “f-root” mode is specified by some other means.

**Comment by michgz** [comment]
Yes "f-root" isn't a table in the usual sense as you say. It works only with certain tables (the "Bass" ones), but apart from that it is completely unconnected from the operation of chord conversion -- as far as I know.

It definitely isn't related to higher-numbered conversion tables and it's already fully supported by the **ac7maker.py** script. Unlike Casio, it's defined separately from conversion table, e.g.

`{"part": 3, "element": 2, "conversion_table": "Bass Basic", "f-root": "On"}`

**Comment by ajcz** [comment]
> and it's already fully supported by the **ac7maker.py** script

Gee...  Should’ve looked closer.
