### ISSUE TITLE
Allow users to specify a midi device (sysex_comms.py)

### ISSUE THREAD

**Issue by ChihHao-Su** [michgz/ac7maker#6]
Script `sysex_comms.py` tries to open `/dev/midi1`, but my casio keyboard is `/dev/midi2` on my pc. I think it should be better to allow the user to specify a midi device with an option.

**Comment by michgz** [comment]
This is a good idea. There's now a parameter "fd" which can take a file device name such as "/dev/midi2". Thanks for the suggestion
